# Generated by Django 3.0.2 on 2020-01-17 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200117_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2020, 1, 17, 20, 17, 45, 154587), verbose_name='Published'),
        ),
    ]
