# Generated by Django 3.0.2 on 2020-01-21 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200120_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 21, 16, 10, 57, 61893), verbose_name='Published'),
        ),
    ]
