# Generated by Django 3.0.2 on 2020-01-21 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200121_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 21, 20, 5, 0, 962075), verbose_name='Published'),
        ),
    ]
