# Generated by Django 3.0.2 on 2020-01-22 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200121_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 22, 18, 42, 31, 490754), verbose_name='Published'),
        ),
    ]
