# Generated by Django 3.0.2 on 2020-01-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15, verbose_name='User')),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Published')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Guest book entry',
                'verbose_name_plural': 'Guest book entries',
                'ordering': ['-date'],
            },
        ),
    ]
