# Generated by Django 3.0.2 on 2020-01-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Short description')),
                ('content', models.TextField(verbose_name='Full description')),
                ('price', models.FloatField(db_index=True, verbose_name='Price $')),
                ('price_acc', models.FloatField(blank=True, null=True, verbose_name='Final price $')),
                ('in_stoke', models.BooleanField(db_index=True, default=True, verbose_name='In stock')),
                ('featured', models.BooleanField(db_index=True, default=True, verbose_name='Recomended')),
                ('image', models.ImageField(upload_to='goods/list', verbose_name='Main image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'good',
                'verbose_name_plural': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/detail', verbose_name='Extra image')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Good')),
            ],
            options={
                'verbose_name': 'image for good',
                'verbose_name_plural': 'images for good',
            },
        ),
    ]
